import React,{useState,useRef,useEffect} from 'react';
import {createRoot} from 'react-dom/client';
import {Search,Sparkles,ArrowUpRight,ArrowUp,ArrowRight,Github,Hash,ShieldCheck,Layers,Clock,LogOut,LoaderCircle,Check,MessageSquare,GitPullRequest,GitCommitHorizontal,SlidersHorizontal,Compass} from 'lucide-react';
import {Button} from '@/components/ui/button';
import {Input} from '@/components/ui/input';
import {Card} from '@/components/ui/card';
import {Badge} from '@/components/ui/badge';
import './index.css';
type Hit={id:string;source:string;documentType:string;title:string;snippet:string;url:string;author:string;container:string;updatedAt:string;score:number;bm25Score?:number;recencyBoost?:number};
type Answer={blocks:{text:string;citations:string[]}[];sources:Hit[];steps:{type:string;query:string;count:number}[];insufficientEvidence:boolean;model:string};
function age(value:string){const t=Date.parse(value);if(!Number.isFinite(t))return 'Date unavailable';const days=Math.max(0,Math.floor((Date.now()-t)/86400000));return days===0?'Today':days===1?'Yesterday':days<30?`${days} days ago`:new Date(t).toLocaleDateString(undefined,{month:'short',day:'numeric',year:'numeric'});}
function sourceIcon(hit:Hit,size=14){return hit.source==='slack'?<Hash size={size}/>:hit.documentType==='pull_request'?<GitPullRequest size={size}/>:hit.documentType==='commit'?<GitCommitHorizontal size={size}/>:<Github size={size}/>;}
function safeLink(url:string){try{const u=new URL(url);return u.protocol==='https:'&&!u.username&&!u.password&&(u.hostname==='github.com'||u.hostname.endsWith('.slack.com'))?url:undefined;}catch{return undefined;}}
function App(){
 const [token,setToken]=useState<string|null>(null),[user,setUser]=useState(''),[query,setQuery]=useState(''),[mode,setMode]=useState<'search'|'ask'>('search'),[source,setSource]=useState('all'),[days,setDays]=useState(0),[sort,setSort]=useState('relevance'),[hits,setHits]=useState<Hit[]>([]),[answer,setAnswer]=useState<Answer|null>(null),[busy,setBusy]=useState(false),[searched,setSearched]=useState(false),[notice,setNotice]=useState(''),[elapsed,setElapsed]=useState(0);
 const abort=useRef<AbortController|null>(null),input=useRef<HTMLInputElement>(null),requestId=useRef(0);
 useEffect(()=>{function keys(e:KeyboardEvent){if(e.key==='/'&&!(e.target instanceof HTMLInputElement)){e.preventDefault();input.current?.focus();}}window.addEventListener('keydown',keys);return()=>window.removeEventListener('keydown',keys);},[]);
 useEffect(()=>{if(!busy)return;const started=Date.now();const t=setInterval(()=>setElapsed(Math.floor((Date.now()-started)/1000)),1000);return()=>clearInterval(t);},[busy]);
 function logout(){requestId.current++;abort.current?.abort();setToken(null);setHits([]);setAnswer(null);setSearched(false);setBusy(false);setNotice('');setQuery('');}
 async function login(e:React.FormEvent<HTMLFormElement>){e.preventDefault();setNotice('');setBusy(true);const f=new FormData(e.currentTarget);try{const r=await fetch('/auth/token',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(Object.fromEntries(f))});if(!r.ok)throw Error('Sign-in failed. Check your username and password.');setToken((await r.json()).access_token);setUser(String(f.get('username')));}catch(e){setNotice((e as Error).message);}finally{setBusy(false);}}
 async function run(q=query,nextMode=mode,filters={source,sinceDays:days,sort}){if(!q.trim()||!token)return;abort.current?.abort();const controller=new AbortController();abort.current=controller;const id=++requestId.current;setBusy(true);setElapsed(0);setNotice('');setAnswer(null);setHits([]);setQuery(q);setSearched(true);setMode(nextMode);
  try{const r=await fetch('/api/'+(nextMode==='ask'?'ask':'search'),{method:'POST',headers:{'Content-Type':'application/json',Authorization:'Bearer '+token},body:JSON.stringify({query:q,...filters}),signal:controller.signal});const data=await r.json();if(id!==requestId.current)return;if(r.status===401){logout();throw Error('Your session expired. Sign in again.');}if(!r.ok){if(r.status===403)throw Error('Access is unavailable or changed during this request. Results have been cleared.');if(r.status===429)throw Error('Search is busy. Please try again shortly.');throw Error(nextMode==='ask'?'The assistant could not produce a verified answer. Try searching directly.':'Search is temporarily unavailable. Please try again.');}if(nextMode==='ask')setAnswer(data);else setHits(data.results);
  }catch(e){if((e as Error).name!=='AbortError')setNotice((e as Error).message);}finally{if(id===requestId.current)setBusy(false);}}
 const number=(id:string)=>answer?answer.sources.findIndex(s=>s.id===id)+1:0;
 const resultCard=(hit:Hit)=><article className="result-card" key={hit.id}><div className="source-line"><span className="source-icon">{sourceIcon(hit)}</span><span>{hit.source==='slack'?'Slack':'GitHub'}</span><span>/</span><span>{hit.container}</span><span className="time-dot"/><span>{hit.documentType.replace('_',' ')}</span></div><a className="result-title" href={safeLink(hit.url)} target="_blank" rel="noopener noreferrer">{hit.title||'Untitled document'}</a><p className="snippet">{hit.snippet}</p><div className="result-footer"><span>{hit.author||'Source document'}</span><span className="time-dot"/><span title={hit.updatedAt}><Clock size={10} className="inline mr-1"/>{age(hit.updatedAt)}</span><a className="score-info" href={safeLink(hit.url)} target="_blank" rel="noopener noreferrer">Open source <ArrowUpRight size={11} className="inline"/></a></div></article>;
 return <div className="app"><aside className="sidebar"><a className="brand" href="/"><Layers size={25}/>context<span className="text-xs font-normal text-[#96a18f]">search</span></a><div className="nav-label">Your workspace</div><button className={'nav '+(mode==='search'?'active':'')} onClick={()=>{setMode('search');setSearched(false);setNotice('');}}><Search size={16}/>Search everything</button><button className={'nav '+(mode==='ask'?'active':'')} onClick={()=>{setMode('ask');setSearched(false);setNotice('');}}><Sparkles size={16}/>Ask your knowledge</button><div className="nav-label">Connected sources</div><div className="source-nav"><Github size={15}/><span>MariHQ / mari</span></div><div className="source-nav"><Hash size={15}/><span>Slack conversations</span></div><div className="account"><div className="avatar">{user?user[0].toUpperCase():'C'}</div><div className="text-xs"><strong>{token?user:'Welcome'}</strong><div className="text-[10px] text-[#8a9b8a]">Knowledge workspace</div></div>{token&&<button className="ml-auto text-[#8a9b8a]" onClick={logout} aria-label="Sign out"><LogOut size={14}/></button>}</div></aside>
 <main className="main"><header className="topbar"><span><span className="mobile-brand">context / search</span><span className="hidden sm:inline">Workspace <span className="mx-3 text-[#b6c1b3]">/</span> {mode==='ask'?'Knowledge assistant':'Search'}</span></span><div className="private-label"><ShieldCheck size={13}/><span>Only what you have access to</span>{token&&<Button variant="ghost" size="sm" onClick={logout} aria-label="Sign out">Sign out</Button>}</div></header>
 <div className="content">{!token?<Card className="login-card"><div className="text-[#548363]"><Compass size={28}/></div><h2>Your team’s knowledge,<br/>all in one place.</h2><p>Sign in to find decisions, conversations, and code changes you can access.</p><form onSubmit={login}><label htmlFor="username">Username</label><Input id="username" name="username" autoComplete="username" required/><label htmlFor="password">Password</label><Input id="password" name="password" type="password" autoComplete="current-password" required/><Button type="submit" disabled={busy}>{busy?<LoaderCircle className="spin"/>:<>Continue <ArrowRight size={15}/></>}</Button></form>{notice&&<div className="notice" role="alert">{notice}</div>}</Card>:<>
 {!searched&&<><div className="greeting">A little clarity for your day</div><h1 className="hero-title">{mode==='ask'?<>Good questions.<br/>Answers with context.</>:<>Everything you know.<br/>Easier to find.</>}</h1><p className="hero-subtitle">Find the conversation, the decision, the change.<br/>Connected knowledge from your team, with the context that matters.</p></>}
 <form className="search-box" onSubmit={e=>{e.preventDefault();run();}}><div className="search-input-row">{mode==='ask'?<Sparkles size={20} className="text-[#85a285]"/>:<Search size={20} className="text-[#8da28f]"/>}<input ref={input} aria-label="Search your knowledge" placeholder={mode==='ask'?'Ask a question about your team’s work…':'Search messages, pull requests, and decisions…'} value={query} onChange={e=>setQuery(e.target.value)} maxLength={500} required/><Button type="submit" size="icon" disabled={busy||!query.trim()} aria-label={mode==='ask'?'Ask assistant':'Search'}>{busy?<LoaderCircle className="spin" size={17}/>:<ArrowUp size={18}/>}</Button></div><div className="search-controls"><SlidersHorizontal size={12} className="text-[#98a596]"/><select aria-label="Source" value={source} onChange={e=>{setSource(e.target.value);if(searched)run(query,mode,{source:e.target.value,sinceDays:days,sort});}}><option value="all">All sources</option><option value="slack">Slack</option><option value="github">GitHub</option></select><select aria-label="Updated date" value={days} onChange={e=>{setDays(Number(e.target.value));if(searched)run(query,mode,{source,sinceDays:Number(e.target.value),sort});}}><option value={0}>Any time</option><option value={7}>Past week</option><option value={30}>Past month</option><option value={90}>Past 3 months</option><option value={365}>Past year</option></select><span className="hint">Press / to focus · Enter to search</span></div></form>
 <div className="mode-tabs"><button className={mode==='search'?'active':''} onClick={()=>{setMode('search');if(searched)run(query,'search');}}><Search size={13}/>Search results</button><button className={mode==='ask'?'active':''} onClick={()=>{setMode('ask');if(searched)run(query,'ask');}}><Sparkles size={13}/>AI answer</button></div>
 {notice&&<div className="notice" role="alert">{notice}</div>}
 {busy&&<div className="loading" role="status"><LoaderCircle size={17} className="spin"/><span>{mode==='ask'?'Searching permitted sources and preparing a cited answer…':'Finding relevant, recent knowledge…'} {elapsed>3&&`${elapsed}s`}</span></div>}
 {!searched&&!busy&&<><div className="text-[11px] text-[#95a18e] mt-8">A few places to start</div><div className="suggestion-grid"><button className="suggestion" onClick={()=>run('What has changed in Mari recently?','ask')}><Sparkles size={18}/><span>What has changed<br/>in Mari recently?</span></button><button className="suggestion" onClick={()=>run('architecture','search')}><Layers size={18}/><span>Find architecture decisions<br/>and implementation notes</span></button><button className="suggestion" onClick={()=>run('What is the team discussing in Slack?','ask')}><MessageSquare size={18}/><span>Catch up on the team’s<br/>Slack discussions</span></button></div><div className="sources-strip"><span><Github size={13}/>GitHub</span><span className="time-dot"/><span><Hash size={13}/>Slack</span><span className="time-dot"/><span><ShieldCheck size={13}/>Permissions respected</span></div></>}
 {searched&&!busy&&!notice&&mode==='search'&&<><div className="result-meta"><span>{hits.length?`${hits.length} matching results · ranked for relevance and freshness`:'No matching results'}</span><select aria-label="Sort results" value={sort} onChange={e=>{setSort(e.target.value);run(query,mode,{source,sinceDays:days,sort:e.target.value});}}><option value="relevance">Most relevant</option><option value="recent">Most recent</option></select></div>{hits.map(resultCard)}{!hits.length&&<div className="empty"><Search size={25} className="mx-auto mb-4 text-[#a1b29d]"/>Try different keywords or a wider date range.<br/><span className="text-[11px]">Results only include documents you’re permitted to read.</span></div>}</>}
 {searched&&!busy&&!notice&&mode==='ask'&&answer&&<><section className="answer-card"><div className="answer-header"><Sparkles size={17}/>{answer.insufficientEvidence?'More context needed':'An answer, with evidence'}<Badge variant="secondary" className="ml-auto text-[9px] font-normal">Source-grounded</Badge></div>{answer.insufficientEvidence?<p className="answer-block">I couldn’t find enough evidence in the sources you can access. Try naming a project, a decision, or a few specific keywords.</p>:answer.blocks.map((block,i)=><p className="answer-block" key={i}>{block.text}{block.citations.map(id=>{const hit=answer.sources.find(s=>s.id===id);return hit&&<a key={id} className="citation" aria-label={'Citation '+number(id)+': '+hit.title} title={hit.title} href={safeLink(hit.url)} target="_blank" rel="noopener noreferrer">{number(id)}</a>;})}</p>)}{answer.sources.length>0&&<div className="evidence-list">{answer.sources.map((hit,i)=><a key={hit.id} className="evidence-link" href={safeLink(hit.url)} target="_blank" rel="noopener noreferrer">{i+1}. {hit.title}</a>)}</div>}</section><details className="steps"><summary>{answer.steps.length} searches · permissions checked before answering</summary>{answer.steps.map((step,i)=><div className="step" key={i}><Check size={11}/><span>{step.query} · {step.count} results</span></div>)}</details>{answer.sources.length>0&&<><div className="result-meta mt-7"><span>Referenced knowledge</span><span>{answer.sources.length} sources</span></div>{answer.sources.map(resultCard)}</>}</>}
 <div className="fineprint">Built on your context graph. Access checked at search and answer time.<br/>AI answers can make mistakes. Open the cited sources to verify.</div>
 </> }</div></main></div>;
}
createRoot(document.getElementById('root')!).render(<React.StrictMode><App/></React.StrictMode>);
