import React,{useState,useRef,useEffect} from 'react';
import {createRoot} from 'react-dom/client';
import {Search,Sparkles,ArrowUp,ArrowUpRight,ArrowRight,Github,Hash,ShieldCheck,Layers,Clock,LogOut,LoaderCircle,Check,MessageSquare,Plus,Square,ChevronDown,X,Copy,RotateCcw,SlidersHorizontal} from 'lucide-react';
import {Button} from '@/components/ui/button';
import {Input} from '@/components/ui/input';
import {Card} from '@/components/ui/card';
import './index.css';
type Hit={id:string;source:string;documentType:string;title:string;snippet:string;url:string;author:string;container:string;updatedAt:string;score:number};
type Step={type:string;query:string;count:number};
type Answer={blocks:{text:string;citations:string[]}[];sources:Hit[];steps:Step[];insufficientEvidence:boolean;model:string};
type Turn={id:number;question:string;answer:Answer;steps:Step[];status:string;busy:boolean;error:string;stopped?:boolean};
const emptyAnswer=():Answer=>({blocks:[],sources:[],steps:[],insufficientEvidence:false,model:''});
function safeLink(url:string){try{const u=new URL(url);return u.protocol==='https:'&&!u.username&&!u.password&&(u.hostname==='github.com'||u.hostname.endsWith('.slack.com'))?url:undefined;}catch{return undefined;}}
function age(value:string){const t=Date.parse(value);return Number.isFinite(t)?new Date(t).toLocaleDateString(undefined,{month:'short',day:'numeric',year:'numeric'}):'Date unavailable';}
function SourceIcon({hit}:{hit:Hit}){return hit.source==='slack'?<Hash size={14}/>:<Github size={14}/>;}
function errorMessage(code:string,status?:number){
 if(status===401)return 'Your session expired. Sign in again to continue.';
 if(status===403)return 'Your access or a source changed while answering. The response has been cleared. Please try again.';
 if(status===429)return 'The assistant is busy. Please try again in a moment.';
 if(code==='assistant_unavailable')return 'The answer service is temporarily unavailable. Please retry.';
 if(code==='invalid_assistant_citation'||code==='invalid_assistant_answer'||code==='assistant_answer_incomplete')return 'The answer could not be checked against its sources. Please retry; no unchecked answer has been kept.';
 if(code==='query_unavailable')return 'The search service is temporarily unavailable. Please retry.';
 return 'The response was interrupted. Please retry.';
}
function App(){
 const [token,setToken]=useState<string|null>(null),[user,setUser]=useState(''),[query,setQuery]=useState(''),[mode,setMode]=useState<'ask'|'search'>('ask'),[turns,setTurns]=useState<Turn[]>([]),[busy,setBusy]=useState(false),[notice,setNotice]=useState(''),[source,setSource]=useState('all'),[days,setDays]=useState(0),[sort,setSort]=useState('relevance'),[hits,setHits]=useState<Hit[]>([]),[searched,setSearched]=useState(false),[panel,setPanel]=useState<Hit[]|null>(null),[lastSearch,setLastSearch]=useState('');
 const requestId=useRef(0),abort=useRef<AbortController|null>(null),input=useRef<HTMLTextAreaElement|null>(null),bottom=useRef<HTMLDivElement|null>(null),followScroll=useRef(true);
 useEffect(()=>{const keys=(e:KeyboardEvent)=>{if(e.key==='/'&&!(e.target instanceof HTMLInputElement)&&!(e.target instanceof HTMLTextAreaElement)){e.preventDefault();input.current?.focus();}if(e.key==='Escape')setPanel(null);};const scroll=()=>{followScroll.current=window.innerHeight+window.scrollY>=document.documentElement.scrollHeight-220;};window.addEventListener('keydown',keys);window.addEventListener('scroll',scroll);return()=>{window.removeEventListener('keydown',keys);window.removeEventListener('scroll',scroll);};},[]);
 useEffect(()=>{if(busy&&followScroll.current)bottom.current?.scrollIntoView({behavior:'smooth',block:'end'});},[turns,busy]);
 const update=(id:number,fn:(t:Turn)=>Turn)=>setTurns(ts=>ts.map(t=>t.id===id?fn(t):t));
 function stop(){requestId.current++;abort.current?.abort();setBusy(false);setTurns(ts=>ts.map(t=>t.busy?{...t,busy:false,stopped:true,status:'Stopped'}:t));}
 function fresh(next:'ask'|'search'='ask'){stop();setMode(next);setTurns([]);setQuery('');setHits([]);setSearched(false);setNotice('');setPanel(null);input.current?.focus();}
 function logout(){fresh();setToken(null);setUser('');}
 async function login(e:React.FormEvent<HTMLFormElement>){e.preventDefault();setNotice('');setBusy(true);const form=new FormData(e.currentTarget);try{const r=await fetch('/auth/token',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(Object.fromEntries(form))});if(!r.ok)throw Error('Sign-in failed. Check your username and password.');setToken((await r.json()).access_token);setUser(String(form.get('username')));}catch(e){setNotice((e as Error).message);}finally{setBusy(false);}}
 async function run(q=query,nextMode=mode,filters={source,sinceDays:days,sort},prior=turns.filter(t=>!t.error).map(t=>t.question).slice(-6)){
  if(!q.trim()||!token)return;abort.current?.abort();const controller=new AbortController();abort.current=controller;const id=++requestId.current;setBusy(true);setNotice('');setPanel(null);setMode(nextMode);setSearched(true);followScroll.current=true;
  if(nextMode==='ask'){setTurns(ts=>[...ts.map(t=>({...t,busy:false})),{id,question:q,answer:emptyAnswer(),steps:[],status:'Connecting to your knowledge',busy:true,error:''}]);setQuery('');}else{setHits([]);setQuery(q);setLastSearch(q);}
  let done=false;
  try{
   const r=await fetch('/search/api/'+(nextMode==='ask'?'ask':'search'),{method:'POST',headers:{'Content-Type':'application/json',Accept:nextMode==='ask'?'text/event-stream':'application/json',Authorization:'Bearer '+token},body:JSON.stringify({query:q,...filters,history:prior}),signal:controller.signal});
   if(!r.ok){const data=await r.json();throw Object.assign(Error(errorMessage(data.error,r.status)),{status:r.status});}
   if(nextMode==='search'){const data=await r.json();if(id===requestId.current)setHits(data.results);done=true;return;}
   if(!r.body||!r.headers.get('Content-Type')?.includes('text/event-stream'))throw Error('The answer stream is unavailable. Please retry.');
   const reader=r.body.getReader(),decoder=new TextDecoder();let buffer='';
   try{while(true){const part=await reader.read();if(part.done)break;if(id!==requestId.current)return;buffer+=decoder.decode(part.value,{stream:true});let end:number;
    while((end=buffer.indexOf('\n\n'))>=0){const frame=buffer.slice(0,end);buffer=buffer.slice(end+2);const kind=frame.split('\n').find(x=>x.startsWith('event:'))?.slice(6).trim();const dataLines=frame.split('\n').filter(x=>x.startsWith('data:')).map(x=>x.slice(5).trim());if(!dataLines.length)continue;const data=JSON.parse(dataLines.join('\n'));
     if(kind==='error')throw Object.assign(Error(errorMessage(data.error,data.status)),{status:data.status});
     if(kind==='status')update(id,t=>({...t,status:data.message}));
     if(kind==='search')update(id,t=>({...t,steps:[...t.steps,data]}));
     if(kind==='reset')update(id,t=>({...t,answer:emptyAnswer(),status:'Checking the answer again'}));
     if(kind==='block')update(id,t=>({...t,answer:{...t.answer,blocks:[...t.answer.blocks,data.block],sources:data.sources}}));
     if(kind==='done'){done=true;update(id,t=>({...t,answer:data,steps:data.steps,busy:false,status:'Complete'}));}
    }
   }}finally{await reader.cancel().catch(()=>{});reader.releaseLock();}
   if(!done)throw Error('The response was interrupted. Please retry.');
  }catch(e){if(id!==requestId.current)return;const error=e as Error&{status?:number};if(error.name==='AbortError')return;
   if(error.status===401){logout();setNotice(error.message);return;}
   if(error.status===403){setPanel(null);setHits([]);setTurns(ts=>ts.map(t=>({...t,answer:emptyAnswer(),steps:[],busy:false,error:error.message})));}
   else if(nextMode==='ask')update(id,t=>({...t,answer:emptyAnswer(),busy:false,error:error.message}));else setNotice(error.message);
  }finally{if(id===requestId.current){setBusy(false);update(id,t=>({...t,busy:false}));}}
 }
 const composer=(followup=false)=><form className={'composer '+(followup?'followup':'')} onSubmit={e=>{e.preventDefault();run();}}><textarea ref={input} aria-label={followup?'Ask a follow-up':'Ask your work knowledge'} placeholder={followup?'Ask a follow-up…':mode==='ask'?'Ask anything about your work':'Search your connected sources'} value={query} onChange={e=>setQuery(e.target.value)} maxLength={500} rows={2} onKeyDown={e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();if(!busy)run();}}}/><div className="composer-footer"><span><ShieldCheck size={13}/>Company knowledge</span>{mode==='search'&&<div className="filters"><SlidersHorizontal size={13}/><select aria-label="Source" value={source} onChange={e=>{setSource(e.target.value);if(searched)run(lastSearch,'search',{source:e.target.value,sinceDays:days,sort});}}><option value="all">All sources</option><option value="github">GitHub</option><option value="slack">Slack</option></select><select aria-label="Updated date" value={days} onChange={e=>{setDays(Number(e.target.value));if(searched)run(lastSearch,'search',{source,sinceDays:Number(e.target.value),sort});}}><option value={0}>Any time</option><option value={7}>Past week</option><option value={30}>Past month</option><option value={90}>Past 3 months</option><option value={365}>Past year</option></select></div>}{busy?<Button type="button" size="icon" onClick={stop} aria-label="Stop response"><Square size={14}/></Button>:<Button type="submit" size="icon" disabled={!query.trim()} aria-label={mode==='ask'?'Send question':'Search'}><ArrowUp size={17}/></Button>}</div></form>;
 return <div className="app"><aside className="sidebar"><a className="brand" href="/search/"><Layers size={26}/>context<span>work AI</span></a><button className="new-chat" onClick={()=>fresh()}><Plus size={16}/>New chat</button><div className="nav-label">Workspace</div><button className={'nav '+(mode==='ask'?'active':'')} onClick={()=>fresh()}><Sparkles size={16}/>Assistant</button><button className={'nav '+(mode==='search'?'active':'')} onClick={()=>fresh('search')}><Search size={16}/>Search</button><div className="nav-label">Connected knowledge</div><div className="source-nav"><Github size={15}/>MariHQ / mari</div><div className="source-nav"><Hash size={15}/>Slack</div><div className="sidebar-note"><ShieldCheck size={16}/><p>Answers from the knowledge<br/>you’re allowed to access.</p></div><div className="account"><div className="avatar">{user?user[0].toUpperCase():'C'}</div><div><strong>{user||'Your workspace'}</strong><span>Context Graph</span></div>{token&&<button onClick={logout} aria-label="Sign out"><LogOut size={15}/></button>}</div></aside>
 <main className="main"><header className="topbar"><div><span className="mobile-brand">context / </span>{mode==='ask'?'Assistant':'Search'}</div><div><button className="mobile-new" onClick={()=>fresh()} aria-label="New chat"><Plus size={17}/></button><span className="private-label"><ShieldCheck size={13}/>Private to you</span>{token&&<button onClick={logout}>Sign out</button>}</div></header>
 {!token?<Card className="login-card"><Sparkles size={26}/><h2>Your work, connected.</h2><p>Sign in with your existing workspace account.</p><form onSubmit={login}><label htmlFor="username">Username</label><Input id="username" name="username" autoComplete="username" required/><label htmlFor="password">Password</label><Input id="password" name="password" type="password" autoComplete="current-password" required/><Button type="submit" disabled={busy}>Continue <ArrowRight size={15}/></Button></form>{notice&&<div className="notice" role="alert">{notice}</div>}</Card>:<div className={'content '+(turns.length&&mode==='ask'?'conversation':'')}>
 {mode==='ask'&&!turns.length&&<section className="welcome"><div className="welcome-symbol"><Sparkles size={30}/></div><h1>What would you like to know?</h1><p>Bring your team’s knowledge into the conversation.</p>{composer()}<div className="suggestions"><button onClick={()=>run('What is Mari?','ask')}><Layers size={17}/><span>Get to know Mari<small>Understand the project and its direction</small></span><ArrowUpRight size={14}/></button><button onClick={()=>run('What has changed in Mari recently?','ask')}><Clock size={17}/><span>Catch up on changes<small>Recent fixes, decisions, and progress</small></span><ArrowUpRight size={14}/></button><button onClick={()=>run('What is the team discussing in Slack?','ask')}><MessageSquare size={17}/><span>Connect the conversation<small>Find context across your team’s discussions</small></span><ArrowUpRight size={14}/></button></div></section>}
 {mode==='ask'&&turns.map((turn,index)=><section className="turn" key={turn.id}><h2 className="question">{turn.question}</h2><div className="assistant-label"><span><Sparkles size={17}/></span>Context</div>{(turn.busy||turn.steps.length>0)&&<details className="activity" open={turn.busy?true:undefined}><summary>{turn.busy?<LoaderCircle size={13} className="spin"/>:<Check size={13}/>}<span role={turn.busy?'status':undefined}>{turn.busy?turn.status:`Searched your knowledge · ${turn.steps.length} searches`}</span><ChevronDown size={12}/></summary>{turn.steps.map((step,i)=><div className="activity-step" key={i}><Search size={12}/><span>{step.query}</span><small>{step.count} results</small></div>)}</details>}
 <div className="answer-body" aria-live="polite">{turn.answer.blocks.map((block,i)=><p className="answer-block" key={i}>{block.text}{block.citations.map(id=>{const hit=turn.answer.sources.find(s=>s.id===id);return hit&&<button key={id} className="citation" title={hit.title} aria-label={'Source: '+hit.title} onClick={()=>setPanel([hit])}>{turn.answer.sources.findIndex(s=>s.id===id)+1}</button>;})}</p>)}</div>
 {turn.busy&&!turn.answer.blocks.length&&<div className="answer-skeleton" aria-hidden="true"><i/><i/><i/></div>}
 {turn.error&&<div className="notice" role="alert">{turn.error}<button onClick={()=>run(turn.question,'ask',undefined,turns.slice(0,index).map(t=>t.question).slice(-6))}><RotateCcw size={13}/>Retry</button></div>}
 {!turn.busy&&!turn.error&&turn.answer.insufficientEvidence&&<p className="no-evidence">I couldn’t find enough evidence in your accessible sources to answer that. Try a project name, a specific change, or a conversation topic.</p>}
 {turn.answer.sources.length>0&&<div className="source-strip">{turn.answer.sources.slice(0,3).map(hit=><button key={hit.id} onClick={()=>setPanel([hit])}><SourceIcon hit={hit}/><span>{hit.title}</span></button>)}<button className="all-sources" onClick={()=>setPanel(turn.answer.sources)}>Sources · {turn.answer.sources.length}<ChevronDown size={12}/></button></div>}
 {!turn.busy&&turn.answer.blocks.length>0&&<div className="answer-actions"><button aria-label="Copy answer" onClick={()=>navigator.clipboard.writeText(turn.answer.blocks.map(b=>b.text).join('\n\n')).catch(()=>setNotice('Could not copy. Select the answer text to copy it.'))}><Copy size={14}/></button><span>{turn.stopped?'Response stopped':'Check the sources for important details.'}</span></div>}</section>)}
 {mode==='ask'&&turns.length>0&&<div className="followup-area">{composer(true)}<p className="fineprint">Answers use your connected sources. AI can make mistakes.</p></div>}
 {mode==='search'&&<><h1 className="search-heading">Find it across your work.</h1>{composer()}{notice&&<div className="notice" role="alert">{notice}</div>}{busy&&<div className="loading" role="status"><LoaderCircle size={15} className="spin"/>Searching your sources…</div>}{searched&&!busy&&<><div className="result-meta"><span>{hits.length} results</span><select aria-label="Sort results" value={sort} onChange={e=>{setSort(e.target.value);run(lastSearch,'search',{source,sinceDays:days,sort:e.target.value});}}><option value="relevance">Most relevant</option><option value="recent">Most recent</option></select><button onClick={()=>run(lastSearch,'ask')}>Ask about this <ArrowRight size={13}/></button></div>{hits.map(hit=><article className="result-card" key={hit.id}><div className="source-line"><SourceIcon hit={hit}/>{hit.source==='github'?'GitHub':'Slack'}<span>/ {hit.container}</span></div><a href={safeLink(hit.url)} target="_blank" rel="noopener noreferrer">{hit.title}</a><p>{hit.snippet}</p><small>{hit.author} · {age(hit.updatedAt)}</small></article>)}{!hits.length&&<p className="no-evidence">No matches. Try different keywords or a wider date range.</p>}</>}</>}
 <div ref={bottom}/></div>}</main>
 {panel&&<div className="source-overlay" onClick={()=>setPanel(null)}><aside className="source-panel" role="dialog" aria-modal="true" aria-label="Answer sources" onClick={e=>e.stopPropagation()}><header><h2>Sources</h2><button aria-label="Close sources" onClick={()=>setPanel(null)}><X size={18}/></button></header><p className="panel-caption">Evidence behind this answer</p>{panel.map(hit=><article key={hit.id}><div className="source-line"><SourceIcon hit={hit}/>{hit.source==='github'?'GitHub':'Slack'} · {hit.container}</div><h3>{hit.title}</h3><small>{hit.author} · {age(hit.updatedAt)}</small><p>{hit.snippet}</p><a href={safeLink(hit.url)} target="_blank" rel="noopener noreferrer">Open original <ArrowUpRight size={14}/></a></article>)}</aside></div>}
 </div>;
}
createRoot(document.getElementById('root')!).render(<React.StrictMode><App/></React.StrictMode>);
