"""Bounded AX retrieval tasks. Capabilities authorize fixed searches, never arbitrary APIs.

Runs are ephemeral and owned by one serving pod. A restart revokes all capabilities;
there is deliberately no claim of durable background execution in this first slice.
"""
import base64,hashlib,ipaddress,json,os,queue,secrets,subprocess,threading,time
from dataclasses import dataclass,field
import server
RUNS={};LOCK=threading.Lock()
@dataclass
class Run:
    token:str
    plans:list
    deadline:float
    documents:dict=field(default_factory=dict)
    steps:list=field(default_factory=list)
    used:set=field(default_factory=set)
    events:queue.Queue=field(default_factory=lambda:queue.Queue(16))
    lock:threading.Lock=field(default_factory=threading.Lock)
    finished:bool=False

def ax(*args,payload=None):
    address=os.environ.get('AX_SERVER')
    if not address:raise server.Denied(503,'ax_unavailable')
    try:
        result=subprocess.run([os.environ.get('AX_BINARY','/usr/local/bin/ax'),'--server',address,'--atespace',os.environ.get('AX_ATESPACE','context-search'),*args],input=json.dumps(payload) if payload else None,text=True,capture_output=True,timeout=15)
    except (OSError,subprocess.TimeoutExpired):raise server.Denied(503,'ax_unavailable') from None
    if result.returncode:raise server.Denied(503,'ax_unavailable')
    return result.stdout

def task_failed(name):
    # The pinned AX CLI's list output contains status only, never task credentials.
    for line in ax('get','tasks').splitlines()[1:]:
        fields=line.split()
        if len(fields)>=3 and fields[0]==name:
            return fields[2].lower()=='failed'
    return False

def task_spec(name,cap,plans):
    # Origin is fixed by deployment, never supplied by a user or generated by a model.
    address=os.environ.get('AX_CALLBACK_HOST') or str(ipaddress.ip_address(os.environ['POD_IP']))
    values={'RUN_CAPABILITY':cap,'CALLBACK_IP':address,'CALLBACK_PORT':os.environ.get('AX_CALLBACK_PORT','8443'),'CALLBACK_TLS_NAME':os.environ.get('CALLBACK_TLS_NAME','search-api'),
      'CALLBACK_CA':base64.b64encode((server.ROOT/'ca.crt').read_bytes()).decode(),'SEARCH_COUNT':str(len(plans))}
    return {'apiVersion':'ax.io/v1alpha1','kind':'Task','metadata':{'name':name,'atespace':os.environ.get('AX_ATESPACE','context-search')},
      'spec':{'image':os.environ['AX_INVESTIGATOR_IMAGE'],'command':['python','/app/investigator.py'],
        'env':[{'name':k,'value':v} for k,v in values.items()], 'resources':{'requests':{'cpu':'100m','memory':'128Mi'},'limits':{'cpu':'1','memory':'256Mi'}},'debug':False}}

def investigate(token,body,emit):
    query=body.get('query');source=body.get('source','all');days=body.get('sinceDays',0)
    if not isinstance(query,str) or not 1<=len(query.strip())<=500 or source not in ('all','github','slack') or type(days)!=int or not 0<=days<=3650:raise server.Denied(400,'invalid_query')
    server.gql(token,'{schemas{name}}')
    if not all(os.environ.get(k) for k in ('AX_SERVER','AX_INVESTIGATOR_IMAGE','POD_IP')):raise server.Denied(503,'ax_unavailable')
    emit('status',{'message':'Planning an investigation'})
    plans=[{'query':query,'source':s,'days':days} for s in (('github','slack') if source=='all' else (source,))]
    message=server.complete([{'role':'system','content':'Plan at most three additional lexical searches for this workplace investigation. Return JSON {"queries":["short keywords"]}. Do not answer the question.'},{'role':'user','content':query}])
    try:extra=json.loads(message.get('content','{}')).get('queries',[])
    except (ValueError,AttributeError):extra=[]
    if isinstance(extra,list):
        for q in extra[:3]:
            if isinstance(q,str) and 1<=len(q.strip())<=500 and q.strip()!=query.strip():plans.append({'query':q,'source':source,'days':days})
    cap=secrets.token_urlsafe(32);key=hashlib.sha256(cap.encode()).hexdigest();name='investigate-'+secrets.token_hex(10)
    run=Run(token,plans,time.monotonic()+120)
    with LOCK:RUNS[key]=run
    try:
        ax('apply','-f','-',payload=task_spec(name,cap,plans))
        emit('status',{'message':'Starting AX investigation','taskId':name})
        while time.monotonic()<run.deadline:
            try:kind,data=run.events.get(timeout=4)
            except queue.Empty:
                if task_failed(name):raise server.Denied(503,'ax_task_failed')
                server.gql(token,'{schemas{name}}')
                emit('status',{'message':'Waiting for AX investigation','taskId':name});continue
            if kind=='finished':
                server.recheck(token,run.documents)
                emit('status',{'message':'Checking investigation sources'})
                return server.synthesize(token,query,run.documents,run.steps,emit)
            if kind=='failed':raise server.Denied(data.get('status',503),data.get('code','ax_task_failed'))
            emit(kind,data)
        raise server.Denied(503,'ax_task_timeout')
    finally:
        with LOCK:RUNS.pop(key,None)
        try:ax('delete','task',name)
        except server.Denied:pass # The capability is already revoked, even if cleanup fails.

def callback(handler):
    token=handler.headers.get('Authorization','')
    if not token.startswith('Bearer ') or len(token)>256:raise server.Denied(401)
    key=hashlib.sha256(token[7:].encode()).hexdigest()
    with LOCK:run=RUNS.get(key)
    if run is None or time.monotonic()>=run.deadline:raise server.Denied(401)
    handler.connection.settimeout(45)
    size=int(handler.headers.get('Content-Length','0'))
    if handler.headers.get('Transfer-Encoding') or not 0<size<=1024:raise server.Denied(400)
    body=json.loads(handler.rfile.read(size))
    if not isinstance(body,dict):raise server.Denied(400)
    with run.lock:
        if run.finished:raise server.Denied(409)
        if handler.path=='/internal/investigation/search':
            index=body.get('index')
            if set(body)!={'index'} or type(index)!=int or not 0<=index<len(run.plans) or index in run.used:raise server.Denied(403)
            run.used.add(index);plan=run.plans[index]
            try:
                rows=server.search(run.token,plan['query'],plan['source'],6,plan['days'])
                run.documents.update({d['id']:d for d in rows});server.recheck(run.token,run.documents)
            except server.Denied as error:
                run.finished=True;run.events.put_nowait(('failed',{'status':error.status,'code':error.code}));raise
            step={'type':'search','query':plan['query'],'source':plan['source'],'count':len(rows)}
            run.steps.append(step);run.events.put_nowait(('search',step))
            # Worker needs identifiers and chronology, not source bodies.
            handler.reply(200,{'documents':[{k:d.get(k) for k in ('id','updatedAt','score')} for d in rows]})
        elif handler.path=='/internal/investigation/complete':
            if set(body)!={'indices'} or body['indices']!=list(range(len(run.plans))) or len(run.used)!=len(run.plans):raise server.Denied(400)
            try:server.recheck(run.token,run.documents)
            except server.Denied as error:
                run.finished=True;run.events.put_nowait(('failed',{'status':error.status,'code':error.code}));raise
            run.finished=True;run.events.put_nowait(('finished',{}));handler.reply(200,{'accepted':True})
        else:raise server.Denied(404)
